version: '3.4'

services:

  hahnwebapp:
    image: ${DOCKER_REGISTRY-}hahnwebapp
    container_name: hahnwebapp
    build:
      context: .
      dockerfile: src/Hahn.ApplicatonProcess.July2021.App/Dockerfile
    restart: on-failure
    depends_on:
      - hahnwebapi
    ports:
      - "5002:80"

  hahnwebapi:
    image: ${DOCKER_REGISTRY-}hahnwebapi
    container_name: hahnwebapi
    build:
      context: .
      dockerfile: src/Hahn.ApplicatonProcess.July2021.Web/Dockerfile
    restart: on-failure
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
      - "5001:443"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: hahnwebdatabase
    hostname: 'sqlserver'  
    environment: 
      ACCEPT_EULA: 'Y'  
      SA_PASSWORD: "b3[Db(9q977wV}*+"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433  